image = "/capstor/scratch/cscs/fstrati/sailor/sailor_clariden.sqsh"

mounts = [
  "/capstor",
  "/iopsstor",
  "/users"
]

workdir = "/root/sailor"

[annotations]
com.hooks.aws_ofi_nccl.enabled = "true"
com.hooks.aws_ofi_nccl.variant = "cuda12"
